import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import os
from scipy.optimize import curve_fit
from scipy.signal import find_peaks, peak_widths
import numpy as np
from main import Peak_Integration, Get_Convention, Get_Gradient_Color

"""
next up: organize the bars by loading and time
"""
# Pseudo-Voigt Function
def pseudo_voigt(x, A, mu, sigma, gamma, eta):
    gaussian = (1 - eta) * np.exp(-((x - mu)**2) / (2 * sigma**2))
    lorentzian = eta / (1 + ((x - mu) / gamma)**2)
    return A * (gaussian + lorentzian)

# Function to fit Pseudo-Voigt and plot
def Fit_And_Plot_Pseudo_Voigt_And_A_Bar(readpath):
    # Load consolidated spectra from the CSV generated by the first script
    df_tot = pd.read_csv(readpath)
    
    peak_start = 2100
    peak_stop = 2225
    df_subset = df_tot[(df_tot['cm-1'] >= peak_start) & (df_tot['cm-1'] <= peak_stop)]
    
    # Initialize a dictionary to store fit parameters and 'Peak-Wing Difference' for each dataset
    fit_params_dict = {}
    peak_wing_diff_dict = {}
    
    # Plot initialization for Pseudo-Voigt fit
    plt.figure(figsize=(14, 8))
    
    # Create a color map
    n = len(df_subset.columns[1:])  # Number of datasets
    colors = cm.Reds(np.linspace(0.2, 0.8, n))  # Generate colors from the Reds colormap

    # Fit the Pseudo-Voigt function to each dataset
    for i, (columnname, color) in enumerate(zip(df_subset.columns[1:], colors)):
        y_data = df_subset[columnname].to_numpy()
        x_data = df_subset['cm-1'].to_numpy()
        
        # Initial guess (A, mu, sigma, gamma, eta)
        max_y = max(y_data)
        max_x = x_data[np.argmax(y_data)]
        initial_guess = [max_y, max_x, 10, 10, 0.5]
        
        # Perform curve fitting
        params, _ = curve_fit(pseudo_voigt, x_data, y_data, p0=initial_guess)
        
        # Store the fit parameters
        fit_params_dict[columnname] = params
        
        # Fit the Pseudo-Voigt function and find peak max
        fitted_y = pseudo_voigt(x_data, *params)
        peak_max = max(fitted_y)

        # Find peaks and calculate widths
        peaks, _ = find_peaks(fitted_y)
        if len(peaks) > 0:
            results_half = peak_widths(fitted_y, peaks, rel_height=0.5)
            if len(results_half[2]) > 0 and len(results_half[3]) > 0:
                wing_min_indices = [int(min(max(idx, 0), len(fitted_y) - 1)) for idx in [results_half[2][0], results_half[3][0]]]
                wing_min = min(fitted_y[wing_min_indices])
            else:
                wing_min = min(fitted_y)
        else:
            wing_min = min(fitted_y)

        # Calculate and store the peak-wing difference
        peak_wing_diff = peak_max - wing_min
        peak_wing_diff_dict[columnname] = peak_wing_diff
        
        # Plot the original data and fitted curve using the same color
        plt.plot(x_data, y_data, label=f'Original - {columnname}', color=color)
        plt.plot(x_data, fitted_y, linestyle='--', label=f'Fitted - {columnname}', color=color)
        
    plt.xlabel('Wavenumber (cm-1)', fontsize=14)
    plt.ylabel('Absorbance', fontsize=14)
    plt.title('Pseudo-Voigt Fit', fontsize=16)
    plt.legend()
    plt.grid(True)
    
    print("Fit Parameters: [A, mu, sigma, gamma, eta]")
    for key, value in fit_params_dict.items():
        print(f"{key}: {value}")
    
    # Create DataFrame from the 'Peak-Wing Difference' dictionary
    peak_wing_diff_df = pd.DataFrame(list(peak_wing_diff_dict.items()), columns=['Sample', 'Peak-Wing Difference'])
    
    # Plot the bar graph for 'Peak-Wing Difference'
    plt.figure(figsize=(14, 8))
    plt.bar(peak_wing_diff_df['Sample'], peak_wing_diff_df['Peak-Wing Difference'], color='skyblue', edgecolor='black')
    plt.xlabel('Sample', fontsize=14)
    plt.ylabel('Peak-Wing Difference', fontsize=14)
    plt.title('Peak-Wing Difference for Each Sample', fontsize=16)
    plt.xticks(rotation=30)
    plt.grid(True, axis='y')
    
    plt.show()

def Integrate_And_Plot_Bar_Graph(readpath):
    # Load consolidated spectra from the CSV generated by the first script
    df_tot = pd.read_csv(readpath)

    # Define wavenumber regions of interest for peak integration
    wn_low = [780, 830, 970, 2100, 2930, 3060]
    wn_high = [830, 930, 1150, 2225, 3000, 3080]
    groupname = ['Si-CH3', 'Si-H (bend)', 'Si-O-Si', 'Si-H (stretch)', 'CH3', 'vinyl (C=C)']

    # Create a dataframe to store peak areas
    df_area = pd.DataFrame(index=groupname)

    # Convert wavenumbers to indices
    wn_array = df_tot['cm-1'].to_numpy()

    # Plot initialization and color settings
    color_list = []
    num_samples = len(df_tot.columns) - 1
    for i, columnname in enumerate(df_tot.columns[1:]):  # Skip the 'cm-1' column
        split_columnname = columnname.split("_")
        if len(split_columnname) == 2:
            agent_loading, time_in_seconds = columnname.split("_")[0], columnname.split("_")[1]
        elif len(split_columnname) == 3:
            _, agent_loading, time_in_seconds = columnname.split("_")[0], columnname.split("_")[1], columnname.split("_")[2]
        else:
            print("Error: The column name is not formatted for a 2/3 '_' split")
            break
        

        # Integrate the peak areas
        wn_corrected = df_tot[columnname].to_numpy()
        area = Peak_Integration(wn_corrected, wn_array, wn_low, wn_high)
        df_area[columnname] = area

        # Conditional formatting for colors
        base_color = Get_Convention('agent-loading', agent_loading)
        try:
            color = Get_Gradient_Color(base_color, 1 - i/num_samples)
        except:
            color = 'black'
            print(f"Error: {agent_loading} is not a valid agent loading.")
        color_list.append(color)

    # Plot the bar graph for peak areas
    ax_area = df_area.plot.bar(title='Peak Areas', rot=30, color=color_list, edgecolor='black', linewidth=1)
    ax_area.set_title('Peak Areas')
    plt.show()


    # Export the integrated peak areas to a CSV
    base_name = os.path.basename(readpath)
    name_without_extension = os.path.splitext(base_name)[0]
    new_name = f"{name_without_extension}_peak_areas.csv"
    writepath = os.path.join(os.path.dirname(readpath), new_name)
    df_area.to_csv(writepath)

##----------------------------MAIN CODE START----------------------------##

# readpath = r'exports\230831_cb-cure-crazy-long-scan-cure-extent-compare_consolidated.csv'
readpath = r"exports\CSV_exports\231208_4xCB-loading_KBrTransmission_ambient-cure_consolidated.csv"
Fit_And_Plot_Pseudo_Voigt_And_A_Bar(readpath)
# Integrate_And_Plot_Bar_Graph(readpath)